######### 锚点 start #######
# 策略组相关
pr: &pr { type: select, proxies: [AutoTest, HK, TW, JP, US, SG, Bypass], use: [no_emby_provider] }

prn: &prn { type: select, proxies: [Proxy, HK, TW, JP, US, SG, Bypass] }

prnp: &prnp { type: select, proxies: [US, Proxy, HK, TW, JP, SG, Bypass] }

prnd: &prnd { type: select, proxies: [Proxy, HK, TW, JP, US, SG] }

pre: &pre { type: select, proxies: [SG, TW, US, Emby] }

#这里是订阅更新和延迟测试相关的
p:
  &p {
    type: http,
    interval: 3600,
    health-check:
      {
        enable: true,
        url: http://cp.cloudflare.com/generate_204,
        interval: 300,
      },
  }

######### 锚点 end #######

# url 里填写自己的订阅,名称不能重复
proxy-providers:
  no_emby_provider:
    <<: *p
    url: ""

  emby_provider:
    <<: *p
    url: ""

ipv6: true
allow-lan: true
mixed-port: 7890
unified-delay: false
tcp-concurrent: true
external-controller: 127.0.0.1:9090
external-ui: ui
external-ui-url: "https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"

geodata-mode: true
geox-url:
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/country-lite.mmdb"

find-process-mode: strict
global-client-fingerprint: chrome

profile:
  store-selected: true

sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  skip-domain:
    - "Mijia Cloud"

tun:
  enable: true
  stack: mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-detect-interface: true

proxies:
  - name: "Bypass"
    type: direct
    udp: true
  - name: DNS_Hijack
    type: dns

proxy-groups:
  - { name: Proxy, <<: *pr }
  - { name: Final, type: select, proxies: [Proxy, Bypass] }
  - { name: CDN, type: select, proxies: [Proxy, Bypass] }
  - { name: Download, <<: *prn }
  - { name: Streaming, <<: *prnd }
  - { name: EmbyProxy, <<: *pre }
  - { name: AI, <<: *prnd }
  - { name: Telegram, <<: *prnd }
  - { name: Paypal, <<: *prnp }
  - { name: Speedtest, <<: *prn }
  - { name: Duolingo, <<: *prn }

  #分隔,下面是地区分组
  - {
      name: HK,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(香港|HK|🇭🇰))^((?!(Gamer|emby)).)*$",
    }
  - {
      name: TW,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(台湾|TW|🇹🇼))^((?!(Gamer|emby)).)*$",
    }
  - {
      name: JP,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(日本|JP|🇯🇵))^((?!(Gamer|emby)).)*$",
    }
  - {
      name: US,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(美国|US|🇺🇸))^((?!(Gamer|emby)).)*$",
    }
  - {
      name: SG,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(新加坡|SG|🇸🇬))^((?!(Gamer|emby)).)*$",
    }
  - {
      name: Emby,
      type: url-test,
      include-all-providers: true,
      filter: "(?=.*(emby))^((?!(Gamer)).)*$",
    }
  - {
      name: AutoTest,
      type: url-test,
      include-all-providers: true,
      tolerance: 10,
      filter: "^((?!(Gamer|arm|emby)).)*$",
    }

rules:
  - DST-PORT,53,DNS_Hijack

  # # 北美相关流媒体
  # - RULE-SET,stream_us_non_ip,Streaming
  # - RULE-SET,stream_us_ip,Streaming
  # # 欧洲相关流媒体
  # - RULE-SET,stream_eu_non_ip,Streaming
  # - RULE-SET,stream_eu_ip,Streaming
  # # 日本相关流媒体
  # - RULE-SET,stream_jp_non_ip,Streaming
  # - RULE-SET,stream_jp_ip,Streaming
  # # 韩国相关流媒体
  # - RULE-SET,stream_kr_non_ip,Streaming
  # - RULE-SET,stream_kr_ip,Streaming
  # # 香港相关流媒体
  # - RULE-SET,stream_hk_non_ip,Streaming
  # - RULE-SET,stream_hk_ip,Streaming
  # # 台湾相关流媒体
  # - RULE-SET,stream_tw_non_ip,Streaming
  # - RULE-SET,stream_tw_ip,Streaming
  # 所有流媒体（包括上述所有流媒体）
  - RULE-SET,stream_non_ip,Streaming
  - RULE-SET,stream_ip,Streaming

  # Emby 流媒体
  - RULE-SET,Emby,Emby

  # OpenAI
  - RULE-SET,ai_non_ip,AI
  - RULE-SET,apple_intelligence_non_ip,AI

  # Telegram 加速
  - RULE-SET,telegram_non_ip,Telegram
  - RULE-SET,telegram_ip,Telegram

  # Paypal 加速
  - RULE-SET,PayPal,Paypal

  # 测速分流
  - RULE-SET,speedtest,Speedtest
  - RULE-SET,apple_speedtest,Speedtest

  # Duolingo 分流
  - RULE-SET,duolingo,Duolingo

  # Apple CN
  - RULE-SET,apple_cn_non_ip,Bypass

  # Apple CDN
  - RULE-SET,apple_cdn,Bypass

  # Apple Services
  - RULE-SET,apple_services,Proxy

  # Microsoft CDN
  - RULE-SET,microsoft_cdn_non_ip,Bypass

  # 软件更新、操作系统等大文件下载
  - RULE-SET,download_domainset,Download
  - RULE-SET,download_non_ip,Download

  # 常见静态 CDN
  - RULE-SET,cdn_domainset,Proxy
  - RULE-SET,cdn_non_ip,Proxy

  # Global 全球加速
  - RULE-SET,global_non_ip,Proxy

  # China DIRECT
  - RULE-SET,domestic_non_ip,Bypass
  - RULE-SET,direct_non_ip,Bypass
  - RULE-SET,domestic_ip,Bypass
  - RULE-SET,BOC,Bypass
  - RULE-SET,china_ip,Bypass
  # Only use it if you are using IPv6
  # - RULE-SET,china_ip_ipv6,Bypass

  # Non IP
  - RULE-SET,lan_non_ip,Bypass
  # IP
  - RULE-SET,lan_ip,Bypass

  # GeoIP China
  - GEOIP,CN,Bypass

  - MATCH,Final

rule-anchor:
  classical_text:
    &classical_text {
      type: http,
      behavior: classical,
      format: text,
      interval: 43200,
    }
  domain_text:
    &domain_text {
      type: http,
      behavior: domain,
      format: text,
      interval: 43200,
    }
  ipcidr_text:
    &ipcidr_text {
      type: http,
      behavior: ipcidr,
      format: text,
      interval: 43200,
    }
  classical_default:
    &classical_default {
      type: http,
      behavior: classical,
      interval: 43200,
    }

rule-providers:
    # # 北美相关流媒体
  # stream_us_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_us.txt
  #   path: ./RuleSet/stream_us_non_ip.txt
  # stream_us_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_us.txt
  #   path: ./RuleSet/stream_us_ip.txt
  # # 欧洲相关流媒体
  # stream_eu_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_eu.txt
  #   path: ./RuleSet/stream_eu_non_ip.txt
  # stream_eu_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_eu.txt
  #   path: ./RuleSet/stream_eu_ip.txt
  # # 日本相关流媒体
  # stream_jp_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_jp.txt
  #   path: ./RuleSet/stream_jp_non_ip.txt
  # stream_jp_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_jp.txt
  #   path: ./RuleSet/stream_jp_ip.txt
  # # 韩国相关流媒体
  # stream_kr_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_kr.txt
  #   path: ./RuleSet/stream_kr_non_ip.txt
  # stream_kr_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_kr.txt
  #   path: ./RuleSet/stream_kr_ip.txt
  # # 香港相关流媒体
  # stream_hk_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_hk.txt
  #   path: ./RuleSet/stream_hk_non_ip.txt
  # stream_hk_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_hk.txt
  #   path: ./RuleSet/stream_hk_ip.txt
  # # 台湾相关流媒体
  # stream_tw_non_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/non_ip/stream_tw.txt
  #   path: ./RuleSet/stream_tw_non_ip.txt
  # stream_tw_ip:
  #   <<: *classical_text
  #   url: https://ruleset.skk.moe/Clash/ip/stream_tw.txt
  #   path: ./RuleSet/stream_tw_ip.txt
  # 所有流媒体（包括上述所有流媒体）
  stream_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/stream.txt
    path: ./RuleSet/stream_non_ip.txt
  stream_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/ip/stream.txt
    path: ./RuleSet/stream_ip.txt

  # Telegram 加速
  telegram_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/telegram.txt
    path: ./RuleSet/telegram_non_ip.txt
  telegram_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/ip/telegram.txt
    path: ./RuleSet/telegram_ip.txt

  # BOC
  BOC:
    <<: *classical_default
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BOC/BOC.yaml

  # Apple CN
  apple_cn_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/apple_cn.txt
    path: ./RuleSet/apple_cn_non_ip.txt

  # Apple Service
  apple_services:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/apple_services.txt
    path: ./RuleSet/apple_services.txt

  # Apple CDN
  apple_cdn:
    <<: *domain_text
    url: https://ruleset.skk.moe/Clash/domainset/apple_cdn.txt
    path: ./RuleSet/apple_cdn.txt

  # Microsoft CDN
  microsoft_cdn_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/microsoft_cdn.txt
    path: ./RuleSet/microsoft_cdn_non_ip.txt

  # Paypal 加速
  PayPal:
    <<: *classical_default
    path: ./RuleSet/PayPal.yaml
    url: https://raw.githubusercontent.com/dler-io/Rules/main/Clash/Provider/PayPal.yaml

  # 多邻国
  duolingo:
    <<: *classical_default
    path: ./RuleSet/duolingo.yaml
    url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Duolingo/Duolingo.yaml

  # 软件更新、操作系统等大文件下载
  download_domainset:
    <<: *domain_text
    url: https://ruleset.skk.moe/Clash/domainset/download.txt
    path: ./RuleSet/download_domainset.txt
  download_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/download.txt
    path: ./RuleSet/download_non_ip.txt

  # Speedtest 测速
  speedtest:
    <<: *domain_text
    url: https://ruleset.skk.moe/Clash/domainset/speedtest.txt
    path: ./RuleSet/speedtest.txt

  # Apple 网络测速
  apple_speedtest:
    <<: *domain_text
    url: https://raw.githubusercontent.com/ocd0711/Profiles/refs/heads/master/Clash/Ruleset/AppleSpeedtest.list
    path: ./RuleSet/apple_speedtest.txt

  # 常见静态 CDN
  cdn_domainset:
    <<: *domain_text
    url: https://ruleset.skk.moe/Clash/domainset/cdn.txt
    path: ./RuleSet/cdn_domainset.txt
  cdn_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/cdn.txt
    path: ./RuleSet/cdn_non_ip.txt

  # 内网域名和局域网 IP
  lan_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/lan.txt
    path: ./RuleSet/lan_non_ip.txt
  lan_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/ip/lan.txt
    path: ./RuleSet/lan_ip.txt

  # Emby 流媒体
  Emby:
    <<: *classical_default
    path: ./RuleSet/emby.yaml
    url: https://raw.githubusercontent.com/ocd0711/Profiles/master/Clash/Ruleset/emby-proxy.yaml

  # AI 相关
  ai_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/ai.txt
    path: ./RuleSet/ai_non_ip.txt
  apple_intelligence_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/apple_intelligence.txt
    path: ./RuleSet/apple_intelligence_non_ip.txt

  # Misc
  domestic_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/domestic.txt
    path: ./RuleSet/domestic_non_ip.txt
  direct_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/direct.txt
    path: ./RuleSet/direct_non_ip.txt
  global_non_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/non_ip/global.txt
    path: ./RuleSet/global_non_ip.txt
  domestic_ip:
    <<: *classical_text
    url: https://ruleset.skk.moe/Clash/ip/domestic.txt
    path: ./RuleSet/domestic_ip.txt

  # chnroute CIDR
  china_ip:
    <<: *ipcidr_text
    url: https://ruleset.skk.moe/Clash/ip/china_ip.txt
    path: ./RuleSet/china_ip.txt
  china_ip_ipv6:
    <<: *ipcidr_text
    url: https://ruleset.skk.moe/Clash/ip/china_ip_ipv6.txt
    path: ./RuleSet/china_ipv6.txt